hive:
  cache_cleanup_days: 7
  log_level: INFO
  max_workers: 8
  project_name: hive_project
  session_timeout_minutes: 120
  version: 1.0.0
logging:
  enable_file_logging: true
  log_format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  log_rotation_count: 5
  max_log_size_mb: 10
tmux:
  base_port: 8000
  session_prefix: hive
  window_prefix: worker
